name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

concurrency:
  group: Azure Static Web Apps CI/CD
  cancel-in-progress: true

jobs:
  build_and_deploy_job:
    environment:
      name: Azure
      url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: dgmjr-actions/git-checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Node Modules
        shell: bash
        run: npm install
        working-directory: src/ts
      - name: Compile TypeScript
        shell: bash
        run: tsc
        working-directory: src/ts
      - name: Catalog Schemas
        shell: bash
        run: node catalogschemas.js
        working-directory: src/js
      - name: Webpack
        shell: bash
        run: webpack-cli
        working-directory: src/js
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_FOREST_0DAEFC80F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          skip_app_build: true
          skip_api_build: true
          ###### End of Repository/Build Configurations ######
      # - name: Push Changes Back to the Git Repo
      #   # You may pin to the exact commit or the version.
      #   uses: actions-x/commit@v6
      #   with:
      #     # The committer's email address
      #     email: json@jsonschema.xyz 
      #     # The committer's name
      #     name: JSON Schema dot XYZ
      #     # The commit message
      #     message: Pushing the changes back to git that were made during CI build
      #     # The branch to push the changes back to, defaults to the current branch
      #     # branch: # default is ${{ github.ref }}
      #     # The files to add separated by space, defaults to every file
      #     # files: # default is .
      #     # The repository to push the code to, defaults to origin (e.g. this repository)
      #     # repository: # default is origin
      #     # The token used to push the code, not needed if you push to the same repository
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     # Whether to perform force push
      #     # force: # default is 0
      #     # The working directory that will be used for git commands
      #     directory: .

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_FOREST_0DAEFC80F }}
          action: "close"
